pipeline {
    agent {
        label 's-4vcpu-8gb'
    }
    options {
        timestamps()
        ansiColor('xterm')
        disableConcurrentBuilds()
    }
    stages {
        stage('Create jobs') {
            steps {
                jobDsl(
                    removedViewAction: 'DELETE',
                    removedJobAction: 'DELETE',
                    targets: [
                        'dsl/scripts/*.groovy'
                    ].join("\n"),
                    unstableOnDeprecation: true,
                    sandbox: false,
                )
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
