pipeline {
    agent any
    options {
        timestamps()
        ansiColor('x-term')
        disableConcurrentBuilds()
    }
    stages {
        stage('Create jobs') {
            when {
                anyOf {
                    changeset "dsl/**"
                    triggeredBy 'UserIdCause'
                }
            }
            steps {
                jobDsl(
                    removedViewAction: 'DELETE',
                    removedJobAction: 'DELETE',
                    targets: [
                        'dsl/scripts/*.groovy'
                    ].join("\n"),
                    unstableOnDeprecation: true,
                    sandbox: false,
                )
            }
        }
    }
}
