pipeline {
    agent any
    options {
        timestamps()
        ansiColor('x-term')
    }
    stages {
        stage('Create jobs') {
            steps {
                jobDsl(
                    removedViewAction: 'DELETE',
                    removedJobAction: 'DELETE',
                    sandbox: true,
                    targets: [
                        'dsl/scripts/*.groovy'
                    ].join("\n"),
                    unstableOnDeprecation: true,
                )
            }
        }
    }
}
