import io.jenkins.plugins.casc.ConfigurationAsCode;
import io.jenkins.plugins.casc.CasCGlobalConfig;
import jenkins.model.GlobalConfiguration;
// https://jenkins.ops.vega.xyz/configuration-as-code/reference
// https://jenkins.ops.vega.xyz/configuration-as-code/schema
pipeline {
    agent {
        label 'tiny'
    }
    options {
        timestamps()
        ansiColor('xterm')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }
    stages {
        stage('Apply Config') {
            environment {
                DIGITALOCEAN_TOKEN = credentials('digitalocean-token')
            }
            when {
                anyOf {
                    changeset "jcasc/**"
                    triggeredBy 'UserIdCause'
                }
            }
            steps {
                script {
                    // sh (
                    //     // display current image ids
                    //     script: '''
                    //         wget https://github.com/digitalocean/doctl/releases/download/v1.92.0/doctl-1.92.0-linux-amd64.tar.gz
                    //         tar xf ./doctl-1.92.0-linux-amd64.tar.gz
                    //         mkdir bin
                    //         mv doctl bin/
                    //         chmod +x bin/doctl
                    //         export PATH="$PWD/bin:$PATH"
                    //         doctl --access-token $DIGITALOCEAN_TOKEN compute image list --no-header | grep jenkins-agent | awk '{printf("%s=%s\\n", $2, $1)}'
                    //     '''
                    // )
                    if (env.JENKINS_URL.contains('jenkins.ops.vega.xyz')) {
                        configUrl = 'https://raw.githubusercontent.com/vegaprotocol/jenkins-shared-library/main/jcasc/jenkins.yaml'
                    }
                    else if (env.JENKINS_URL.contains('jenkins.vega.rocks')) {
                        configUrl = 'https://raw.githubusercontent.com/vegaprotocol/jenkins-shared-library/main/jcasc/jenkins-new.yaml'
                    }
                    // copy paste = https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L199
                    def config = GlobalConfiguration.all().get(CasCGlobalConfig.class)
                    if (config != null) {
                        if (config.getConfigurationPath() != configUrl) {
                            config.setConfigurationPath(configUrl)
                            config.save()
                        }
                    } else {
                        error "Couldn't get a CaSC config! Probably you didn't install the plugin or need to set primar configuration manually in the configuration panel"
                    }
                    // https://stackoverflow.com/questions/54770969/jenkins-configuration-as-code-programmatically-reload-configuration-from-file
                    ConfigurationAsCode.get().configure()
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
