REPO_URL = binding.variables.get('GIT_URL')

def standardDefinition(args){
  return {
    cpsScm {
      scm {
        git {
          remote {
            url(args.repo)
            credentials(args.get('credentials', "vega-ci-bot"))
          }
          branch('$BRANCH')
        }
      }
      scriptPath(args.get('jenkinsfile', 'Jenkinsfile'))
    }
  }
}

def standardDescription() {
    def url = REPO_URL.replace(':', '/').replace('git@', 'https://')
    return  """
        <h3>
        This job was automatically generated by DSL script located at <a href="${url}">this repository</a> and processed by <a href='${binding.variables.get('JOB_URL')}'>this job</a>, any manual configuration will be overriden.
        </h3>
    """
}

def createCommonPipeline(args){
    args.repo = "git@github.com:vegaprotocol/${args.repo}.git"
    return pipelineJob(args.name) {
        description(standardDescription())
        parameters {
            gitParameter {
                branch('')
                branchFilter('.*')
                defaultValue("origin/${args.get('branch', 'master')}")
                description('You can choose different branch for testing')
                name('BRANCH')
                quickFilterEnabled(true)
                selectedValue('DEFAULT')
                sortMode('ASCENDING_SMART')
                type('BRANCH')
                tagFilter('*')
                useRepository(args.repo)
            }
        }
        logRotator {
            daysToKeep(45)
        }
        // example
        // triggers: {
        //     cron('H */12 * * *')
        // },
        if (args.triggers) {
            triggers args.triggers
        }
        environmentVariables {
            keepBuildVariables(true)
            keepSystemVariables(true)
            args.env.each { key, value ->
                env(key.toUpperCase(), value)
            }
        }
        definition standardDefinition(args)
    }
}

def jobs = [
    [
        name: 'ansible SSH',
        // parsed on Jenkinsfile level
        env: [
            ANSIBLE_ARGS: '--tags ssh',
            INVENTORY: 'hosts',
            CHANGESET: '(group_vars/all.yaml|roles/accounts/**)'
        ],
        repo: 'ansible',

    ]
]

jobs.each { job ->
    createCommonPipeline(job)
}