"jenkins":
  "nodes":
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins001-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins002-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins002-tiny-2"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "performance-tests"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins003-big-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "big big-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins006-big-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "big big-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins006-big-2"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins006-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
