"jenkins":
  "nodes":
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins001-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins002-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "performance-tests"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins003-performance-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "big big-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins005-big-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "medium medium-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins005-medium-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins005-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins005-tiny-2"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "medium medium-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins006-medium-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "medium medium-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins006-medium-2"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "tiny tiny-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins006-tiny-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "big big-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins007-big-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "medium medium-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins007-medium-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "big big-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins008-big-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
  - "permanent":
      "labelString": "medium medium-office"
      "launcher":
        "inbound":
          "webSocket": true
          "workDirSettings":
            "disabled": false
            "failIfWorkDirIsMissing": false
            "internalDir": "remoting"
      "mode": "EXCLUSIVE"
      "name": "jenkins008-medium-1"
      "remoteFS": "/jenkins"
      "retentionStrategy": "always"
